In [7]:
import numpy as np

Numpy assignment:1

In [8]:
array=np.array([[8,9,10],[11,12,13]])
print(array)

[[ 8  9 10]
 [11 12 13]]


In [9]:
array.reshape(3,2)

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [12]:
Question:2

In [10]:
array=np.array([[8,9],[10,11],[12,13]])
print(array)

[[ 8  9]
 [10 11]
 [12 13]]


In [13]:
array[:2,1]

array([ 9, 11])